### PR TITLE
Update to stable Rust

### PR DESCRIPTION
**Pull request by crumblingstatue**

### CODE REVIEW

**Comment by netvl** [comment]
Thank you very much!

Frankly, I'm not sure about switching form `[T; 1]` to `*mut T`. I didn't work with these bindings for some time, so I can't say for sure now, but I think this was important outside function signatures too. Did you test that crates using gmp-sys (e.g. `mpfr.rs`) have not been broken by this change?

**Comment by crumblingstatue** [comment]
I'm not sure about the `[T; 1]` to `*mut T` change either.

The main problem is that in C, `T[1]` basically decays to `T*` in a function argument position, allowing one to pass `T*` to a function expecting that type. I believe this is the way the C library is intended to be used, but I might be wrong.

This does not work in Rust, however. You can't safely convert `&T` to a `[T; 1]`.

My solution might not be the proper solution though, do you have any better ideas?

Maybe an additional type should be added that the functions would take as argument, and the original type left alone. This would create a type that does not exist in the original C library though, but is a necessity because of the semantic differences between Rust and C.

**Comment by crumblingstatue** [comment]
I only tested the library with [rust-gmp](https://github.com/fizyk20/rust-gmp) so far, which I have locally modified to use these bindings instead of its own.

**Comment by netvl** [comment]
As far as I remember, this is done because in C you will be able to use `mpf_t` as a value, while passing it to functions would automatically convert it to a pointer. Therefore, I think, in Rust it makes more sense to make it just `__mpX_struct` instead of `*mut __mpX_struct`. After all, it is much more important what the type is when it is used for a variable rather than when it is used as a function argument. So I personally think that it is better to leave it as it is; it is not used in GMP public API anyway.

**Comment by crumblingstatue** [comment]
> As far as I remember, this is done because in C you will be able to use mpf_t as a value, while passing it to functions would automatically convert it to a pointer.

Yes.

> Therefore, I think, in Rust it makes more sense to make it just __mpX_struct instead of *mut __mpX_struct. After all, it is much more important what the type is when it is used for a variable rather than when it is used as a function argument.

At least [rust-gmp](https://github.com/fizyk20/rust-gmp) uses `__mp*_struct`s directly instead of `mp*_t` when storing them, so it's not an issue there. Other libraries might try to store `mp*_t` directly though, I haven't checked.

> So I personally think that it is better to leave it as it is; it is not used in GMP public API anyway.

It is extensively used in the public API. Most functions take `mp*_t`s as arguments. Look at https://gmplib.org/manual/Float-Arithmetic.html for example.

Maybe the right solution is to get rid of the `[T;1]` types entirely, since it only makes sense when C semantics are applied, make the `mp*_t`s direct type aliases to the `__mp*_struct`s, and make the functions take pointers to the `mp*_t`s.

**Comment by netvl** [comment]
> It is extensively used in the public API. Most functions take mp*_ts as arguments.

Are you sure? According to the bindgen output, it uses `mpX_ptr` or `mpX_srcptr` everywhere.

**Comment by crumblingstatue** [comment]
You are correct. I should have looked at the bindgen output instead of online documentation.

I'll revert the appropriate changes, then see if I can make rust-gmp work with that API.

**Comment by netvl** [comment]
Thanks! Everything else seems fine to me.

**Comment by crumblingstatue** [comment]
Alright, I have narrowed the problem down to `gmp_randstate_t`, which is actually the only type that behaves problematically, as it doesn't have a `_ptr` or `_srcptr` equivalent that is used in the function signatures.

I must have ran into this error, and incorrectly assumed that all the `_t` types behave this way.

So the previous question applies: How should we solve this?

**Comment by netvl** [comment]
I see. Yes, in this case I think it would make sense to change `gmp_randstate_t` to an alias to the structure it holds, and use raw pointers for the function arguments, possibly with an alias, like `_ptr` and `_srcptr` for other types.

**Comment by crumblingstatue** [comment]
I reverted the previous solutions, and applied the new proposed solution for randstate.

Ready for review.

**Comment by crumblingstatue** [comment]
Hmm, it seems that the build script doesn't emit link information for cargo if the library was found in `check_library`. Let me fix that before this is merged.

**Comment by crumblingstatue** [comment]
Alright, done.

**Comment by netvl** [comment]
> it seems that the build script doesn't emit link information for cargo if the library was found in check_library

As far as I know, this is not required - if the build script did not emit the information, Cargo would use the library name specified in the manifest (the `links = "gmp"` key). But OK, it's fine if it is emitted.

Thank you very much again!

**Comment by crumblingstatue** [comment]
> As far as I know, this is not required - if the build script did not emit the information, Cargo would use the library name specified in the manifest (the links = "gmp" key). But OK, it's fine if it is emitted.

Strange, I had linker errors about undefined reference to gmp stuff until I emitted the information in the build script.

**Comment by crumblingstatue** [comment]
If possible, can you release a new version on crates.io?

**Comment by netvl** [comment]
Hmm, turns out I can't do it. Building with the stable Rust gives the following error:

```
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading libc v0.2.7
   Compiling libc v0.2.7
   Compiling gmp-sys v0.1.0 (file:///Users/netvl/dev/lang/rust/projects/gmp-sys)
src/lib.rs:70:1: 70:53 error: unsupported representation for univariant enum [E0083]
src/lib.rs:70 pub enum Enum_Unnamed4 { GMP_RAND_ALG_DEFAULT = 0, }
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/lib.rs:70:1: 70:53 help: run `rustc --explain E0083` to see a detailed explanation
error: aborting due to previous error
Could not compile `gmp-sys`.

To learn more, run the command again with --verbose.
```

I don't want to release it until it builds with the stable compiler.

I'm willing to look into this, but right now I have to work on something else, so I won't be able to fix this until the evening MSK. You may send another pull request, if you want, in the meanwhile :)

**Comment by netvl** [comment]
@crumblingstatue sorry for the delay. I just have published gmp-sys 0.1.0 on crates.io, with all these fixes and also one which allows it to run with the latest stable.

**Pull request merged**
